name: qlty
on:
  push: { branches: [ "master", "main" ] }
  pull_request:
  schedule:
    - cron: "0 7 * * 1"
  workflow_dispatch: {}

jobs:
  qlty:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    env:
      QLTY_AUTH_TOKEN: ${{ secrets.QLTY_AUTH_TOKEN }}
      MAVEN_OPTS: "-Xmx2g"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Ejecuta tests y genera jacoco.xml, saltando RAT (licencias)
      - name: Test + JaCoCo (skip RAT)
        run: mvn -B -Denforcer.skip=true -Drat.skip=true -DskipITs clean test jacoco:report

      # Instala CLI de Qlty
      - name: Install Qlty CLI
        run: curl -fsSL https://get.qlty.sh | bash

      # Análisis (smells/duplicación/complexity)
      - name: Run Qlty analysis
        run: ~/.qlty/bin/qlty metrics --all .

      # Publicar cobertura JaCoCo en Qlty Cloud
      - name: Publish coverage to Qlty
        run: ~/.qlty/bin/qlty coverage publish target/site/jacoco/jacoco.xml --format jacoco
